//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class AdminDebug
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litDbStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDbStatus;

        /// <summary>
        /// litTableStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTableStatus;

        /// <summary>
        /// litSessionInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSessionInfo;

        /// <summary>
        /// litAuthStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAuthStatus;

        /// <summary>
        /// btnTestLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestLogin;

        /// <summary>
        /// litLoginTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLoginTest;

        /// <summary>
        /// btnCreateAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateAdmin;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>
        /// litRecentActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRecentActivity;
    }
}