//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class AdminSimple
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsername;

        /// <summary>
        /// litUserDisplay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserDisplay;

        /// <summary>
        /// litLoginTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLoginTime;

        /// <summary>
        /// litSessionId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSessionId;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}