//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class AdminTest
    {
        /// <summary>
        /// litUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsername;

        /// <summary>
        /// litUserId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserId;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litLoginTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLoginTime;

        /// <summary>
        /// litSessionValid control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSessionValid;

        /// <summary>
        /// litFormsAuth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFormsAuth;

        /// <summary>
        /// litSessionId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSessionId;
    }
}