//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class RedirectTest
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// btnRedirectToAdminTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRedirectToAdminTest;

        /// <summary>
        /// btnRedirectToAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRedirectToAdmin;

        /// <summary>
        /// litSessionInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSessionInfo;
    }
}